const products = [
  {
    id: 1,
    name: "Bolu Susun",
    description: "di susun dengan penuh kenangan",
    originalPrice: 40000,
    discountPercent: 10,
    category: "Bolu",
    image: "Bolu.png",
  },
  {
    id: 2,
    name: "Mie Aceh",
    description: "tratak tungtung jess",
    originalPrice: 29000,
    discountPercent: 5,
    category: "Bolu",
    image: "mie aceh.png",
  },
  {
    id: 3,
    name: "Bolu Lapis",
    description: "Legiitt",
    originalPrice: 40000,
    discountPercent: 0,
    category: "Mie",
    image: "bolu lapis.png",
  },
  {
    id: 4,
    name: "Donat",
    description: "Rasa Donat",
    originalPrice: 10000,
    discountPercent: 0,
    category: "Bolu",
    image: "donat.png",
  },
  {
    id: 5,
    name: "pizza Hut",
    description: "potongan penuh nikmat",
    originalPrice: 50000,
    discountPercent: 0,
    category: "Pizza",
    image: "pizza hut.png",
  },
  {
    id: 6,
    name: "Mata Sapi",
    description: "telur dadar",
    originalPrice: 4000,
    discountPercent: 0,
    category: "Lauk",
    image: "Mata Sapi.png",
  },
  {
    id: 7,
    name: "Es cream",
    description: "telur dadar",
    originalPrice: 4000,
    discountPercent: 0,
    category: "Dessert",
    image: "Mata Sapi.png",
  },
  {
    id: 8,
    name: "Nasi Goreng",
    description: "telur dadar",
    originalPrice: 4000,
    discountPercent: 0,
    category: "Main",
    image: "Mata Sapi.png",
  },
  {
    id: 9,
    name: "Sayur Sop",
    description: "telur dadar",
    originalPrice: 4000,
    discountPercent: 0,
    category: "Lauk",
    image: "Mata Sapi.png",
  },
  {
    id: 10,
    name: "Martabak",
    description: "telur dadar",
    originalPrice: 4000,
    discountPercent: 0,
    category: "Dessert",
    image: "Mata Sapi.png",
  },
];

export default products;
